domain_path: C:\Image_Processing_FPGA\fpga\vitis_app\multi_filter_platform\export\multi_filter_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
