# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/filter_bd.bd
# Block Designs: The module: 'filter_bd' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_processing_system7_0_0/filter_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_processing_system7_0_0 || ORIG_REF_NAME==filter_bd_processing_system7_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_multi_filter_0_0/filter_bd_multi_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_multi_filter_0_0 || ORIG_REF_NAME==filter_bd_multi_filter_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/filter_bd_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_axi_smc_1 || ORIG_REF_NAME==filter_bd_axi_smc_1} -quiet] -quiet

# Block Designs: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/bd_dff4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_0/bd_dff4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_2/bd_dff4_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_3/bd_dff4_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_4/bd_dff4_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_5/bd_dff4_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_6/bd_dff4_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_7/bd_dff4_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_8/bd_dff4_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_9/bd_dff4_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_10/bd_dff4_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_11/bd_dff4_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_12/bd_dff4_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_13/bd_dff4_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_14/bd_dff4_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_15/bd_dff4_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_16/bd_dff4_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_17/bd_dff4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_18/bd_dff4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_19/bd_dff4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_20/bd_dff4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_21/bd_dff4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_22/bd_dff4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_23/bd_dff4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_24/bd_dff4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_25/bd_dff4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_26/bd_dff4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_27/bd_dff4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_28/bd_dff4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_29/bd_dff4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_30/bd_dff4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_31/bd_dff4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_32/bd_dff4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_33/bd_dff4_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_34/bd_dff4_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_35/bd_dff4_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_36/bd_dff4_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_37/bd_dff4_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_38/bd_dff4_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_39/bd_dff4_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_processing_system7_0_0/filter_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_processing_system7_0_0 || ORIG_REF_NAME==filter_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_multi_filter_0_0/constraints/multi_filter_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_2/bd_dff4_arinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_3/bd_dff4_rinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_4/bd_dff4_awinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_5/bd_dff4_winsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_6/bd_dff4_binsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_7/bd_dff4_aroutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_8/bd_dff4_routsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_9/bd_dff4_awoutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_10/bd_dff4_woutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_11/bd_dff4_boutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_12/bd_dff4_arni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_13/bd_dff4_rni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_14/bd_dff4_awni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_15/bd_dff4_wni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_16/bd_dff4_bni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_20/bd_dff4_s00a2s_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_21/bd_dff4_sarn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_22/bd_dff4_srn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_23/bd_dff4_sawn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_24/bd_dff4_swn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_25/bd_dff4_sbn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_26/bd_dff4_m00s2a_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_27/bd_dff4_m00arn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_28/bd_dff4_m00rn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_29/bd_dff4_m00awn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_30/bd_dff4_m00wn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_31/bd_dff4_m00bn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_33/bd_dff4_m01s2a_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_34/bd_dff4_m01arn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_35/bd_dff4_m01rn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_36/bd_dff4_m01awn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_37/bd_dff4_m01wn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_38/bd_dff4_m01bn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_smc_1 || ORIG_REF_NAME==filter_bd_axi_smc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/filter_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter_bd'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/filter_bd.bd
# Block Designs: The module: 'filter_bd' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_processing_system7_0_0/filter_bd_processing_system7_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_processing_system7_0_0 || ORIG_REF_NAME==filter_bd_processing_system7_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_multi_filter_0_0/filter_bd_multi_filter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_multi_filter_0_0 || ORIG_REF_NAME==filter_bd_multi_filter_0_0} -quiet] -quiet

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/filter_bd_axi_smc_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_axi_smc_1 || ORIG_REF_NAME==filter_bd_axi_smc_1} -quiet] -quiet

# Block Designs: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/bd_dff4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_0/bd_dff4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_2/bd_dff4_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_3/bd_dff4_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_4/bd_dff4_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_5/bd_dff4_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_6/bd_dff4_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_7/bd_dff4_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_8/bd_dff4_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_9/bd_dff4_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_10/bd_dff4_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_11/bd_dff4_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_12/bd_dff4_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_13/bd_dff4_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_14/bd_dff4_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_15/bd_dff4_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_16/bd_dff4_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_17/bd_dff4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_18/bd_dff4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_19/bd_dff4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_20/bd_dff4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_21/bd_dff4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_22/bd_dff4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_23/bd_dff4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_24/bd_dff4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_25/bd_dff4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_26/bd_dff4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_27/bd_dff4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_28/bd_dff4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_29/bd_dff4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_30/bd_dff4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_31/bd_dff4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_32/bd_dff4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_33/bd_dff4_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_34/bd_dff4_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_35/bd_dff4_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_36/bd_dff4_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_37/bd_dff4_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_38/bd_dff4_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_39/bd_dff4_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.srcs/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_processing_system7_0_0/filter_bd_processing_system7_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_processing_system7_0_0 || ORIG_REF_NAME==filter_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_dma_0_0/filter_bd_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_dma_0_0 || ORIG_REF_NAME==filter_bd_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_multi_filter_0_0/constraints/multi_filter_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_1/bd_dff4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_2/bd_dff4_arinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_3/bd_dff4_rinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_4/bd_dff4_awinsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_5/bd_dff4_winsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_6/bd_dff4_binsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_7/bd_dff4_aroutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_8/bd_dff4_routsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_9/bd_dff4_awoutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_10/bd_dff4_woutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_11/bd_dff4_boutsw_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_12/bd_dff4_arni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_13/bd_dff4_rni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_14/bd_dff4_awni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_15/bd_dff4_wni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_16/bd_dff4_bni_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_20/bd_dff4_s00a2s_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_21/bd_dff4_sarn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_22/bd_dff4_srn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_23/bd_dff4_sawn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_24/bd_dff4_swn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_25/bd_dff4_sbn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_26/bd_dff4_m00s2a_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_27/bd_dff4_m00arn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_28/bd_dff4_m00rn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_29/bd_dff4_m00awn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_30/bd_dff4_m00wn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_31/bd_dff4_m00bn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_33/bd_dff4_m01s2a_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_34/bd_dff4_m01arn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_35/bd_dff4_m01rn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_36/bd_dff4_m01awn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_37/bd_dff4_m01wn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/bd_0/ip/ip_38/bd_dff4_m01bn_0_ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/ooc.xdc

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_axi_smc_1/smartconnect.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_axi_smc_1 || ORIG_REF_NAME==filter_bd_axi_smc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/ip/filter_bd_rst_ps7_0_50M_1/filter_bd_rst_ps7_0_50M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==filter_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==filter_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Image_Processing_FPGA/fpga/vivado_project/filter_vivado/filter_vivado.gen/sources_1/bd/filter_bd/filter_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter_bd'. Do not add the DONT_TOUCH constraint.
